spring.application.name=grader
server.port=8082

# MySQL
spring.datasource.url=${DB_URL:jdbc:mysql://localhost:3307/zombie_hunter?serverTimezone=Asia/Seoul}
spring.datasource.username=${DB_USERNAME:root}
spring.datasource.password=${DB_PASSWORD:root}
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

# JPA
spring.jpa.hibernate.ddl-auto=validate
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQLDialect

# Flyway
spring.flyway.enabled=true
spring.flyway.locations=classpath:db/migration
